[package]
name = "m68k-linter"
version = "0.1.0"
authors = ["hadi tarhini <hi@how.hadi.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
